import 'package:hive/hive.dart';
import 'package:flutter/material.dart'; // For TimeOfDay

part 'reminder.g.dart'; // This file is generated by running the build runner

@HiveType(typeId: 1) // Unique typeId for this model
class Reminder extends HiveObject {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final String title;

  @HiveField(2)
  final String description;

  @HiveField(3)
  final TimeOfDay time;

  @HiveField(4) // New field for image string
  final String image;

  Reminder({
    required this.id,
    required this.title,
    required this.description,
    required this.time,
    required this.image, // Add image to constructor
  });
}
